const wallpapers = [
    {'file': 'img/1.jpeg', 'name': 'Textures', 'describe': 'Beautiful textures'},
    {'file': 'img/2.jpeg', 'name': 'Shore', 'describe': 'Scenic shoreline'},
    {'file': 'img/3.jpeg', 'name': 'Ball', 'describe': 'Playful ball'},
    {'file': 'img/4.jpeg', 'name': 'Space car', 'describe': 'Futuristic space car'},
    {'file': 'img/5.jpeg', 'name': 'Chess', 'describe': 'Chessboard'},
    {'file': 'img/6.jpeg', 'name': 'Christmas', 'describe': 'Christmas decorations'},
    {'file': 'img/7.jpeg', 'name': 'New-York', 'describe': 'New York cityscape'},
    {'file': 'img/8.jpeg', 'name': 'Winter', 'describe': 'Winter wonderland'},
    {'file': 'img/9.jpeg', 'name': 'Tale', 'describe': 'Magical fairy tale'},
    {'file': 'img/animals1.jpeg', 'name': 'Wolf', 'describe': 'Majestic wolf'},
    {'file': 'img/animals2.jpeg', 'name': 'Cat', 'describe': 'Cute cat'},
    {'file': 'img/animals3.jpeg', 'name': 'Lynx', 'describe': 'Wild lynx'},
    {'file': 'img/animals4.jpeg', 'name': 'Raccoon', 'describe': 'Playful raccoon'},
    {'file': 'img/animals5.jpeg', 'name': 'Dog', 'describe': 'Loyal dog'},
    {'file': 'img/animals6.jpeg', 'name': 'Wolf on a mountain', 'describe': 'Wolf on a mountain'},
    {'file': 'img/animals7.jpeg', 'name': 'Kitty', 'describe': 'Adorable kitty'},
    {'file': 'img/animals8.jpeg', 'name': 'Wolves', 'describe': 'Pack of wolves'},
    {'file': 'img/animals9.jpeg', 'name': 'Black cat', 'describe': 'Mysterious black cat'},
    {'file': 'img/auto1.jpeg', 'name': 'BMW', 'describe': 'Sleek BMW car'},
    {'file': 'img/auto2.jpeg', 'name': 'BMW Black', 'describe': 'Black BMW'},
    {'file': 'img/auto3.jpeg', 'name': 'BWM Night', 'describe': 'BMW at night'},
    {'file': 'img/auto4.jpeg', 'name': 'Sportcar', 'describe': 'Sporty car'},
    {'file': 'img/auto5.jpeg', 'name': 'Sportcar 2', 'describe': 'Another sporty car'},
    {'file': 'img/auto6.jpeg', 'name': 'Track car', 'describe': 'Track racing car'},
    {'file': 'img/auto7.jpeg', 'name': 'Mercedess', 'describe': 'Mercedes-Benz'},
    {'file': 'img/auto8.jpeg', 'name': 'Porsche', 'describe': 'Luxury Porsche car'},
    {'file': 'img/auto9.jpeg', 'name': 'Speed car', 'describe': 'High-speed racing car'},
    {'file': 'img/food1.jpeg', 'name': 'Fika', 'describe': 'Fika time'},
    {'file': 'img/food2.jpeg', 'name': 'Cozy caffe', 'describe': 'Cozy cafe'},
    {'file': 'img/food3.jpeg', 'name': 'Caffe Latte', 'describe': 'Caffe Latte'},
    {'file': 'img/food4.jpeg', 'name': 'Strawberries', 'describe': 'Fresh strawberries'},
    {'file': 'img/food5.jpeg', 'name': 'Orange', 'describe': 'Juicy orange'},
    {'file': 'img/food6.jpeg', 'name': 'Pineapple', 'describe': 'Tropical pineapple'},
    {'file': 'img/food7.jpeg', 'name': 'Candy', 'describe': 'Colorful candy'},
    {'file': 'img/food8.jpeg', 'name': 'Fruits', 'describe': 'Assorted fruits'},
    {'file': 'img/food9.jpeg', 'name': 'Strawberries 2', 'describe': 'More strawberries'},
    {'file': 'img/nature1.jpeg', 'name': 'Forest', 'describe': 'Mystical forest'},
    {'file': 'img/nature2.jpeg', 'name': 'Night sky', 'describe': 'Starry night sky'},
    {'file': 'img/nature3.jpeg', 'name': 'Morning nature', 'describe': 'Morning in nature'},
    {'file': 'img/nature4.jpeg', 'name': 'Winter nature', 'describe': 'Winter in the wild'},
    {'file': 'img/nature5.jpeg', 'name': 'Autumn', 'describe': 'Beautiful autumn'},
    {'file': 'img/nature6.jpeg', 'name': 'Fantasy', 'describe': 'Fantasy landscape'},
    {'file': 'img/nature7.jpeg', 'name': 'River', 'describe': 'Tranquil river'},
    {'file': 'img/nature8.jpeg', 'name': 'Dream', 'describe': 'Dreamy landscape'},
    {'file': 'img/nature9.jpeg', 'name': 'Road', 'describe': 'Endless road'},
    {'file': 'img/space1.jpeg', 'name': 'Space', 'describe': 'Outer space'},
    {'file': 'img/space2.jpeg', 'name': 'Space 2', 'describe': 'More outer space'},
    {'file': 'img/space3.jpeg', 'name': 'Space 3', 'describe': 'Even more outer space'},
    {'file': 'img/space4.jpeg', 'name': 'Space 4', 'describe': 'Space exploration'},
    {'file': 'img/space5.jpeg', 'name': 'Space 5', 'describe': 'Galactic beauty'},
    {'file': 'img/space6.jpeg', 'name': 'Space 6', 'describe': 'Infinite space'},
    {'file': 'img/space7.jpeg', 'name': 'Space 7', 'describe': 'Space adventure'},
    {'file': 'img/space8.jpeg', 'name': 'Space 8', 'describe': 'Journey to the stars'},
    {'file': 'img/space9.jpeg', 'name': 'Space 9', 'describe': 'Celestial wonders'}
  ];  

  export default wallpapers;